# Generated by Django 5.0 on 2024-01-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_dadospaciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadospaciente',
            old_name='coleterol_totl',
            new_name='coleterol_total',
        ),
    ]
