# Generated by Django 5.0 on 2024-01-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_rename_coleterol_totl_dadospaciente_coleterol_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospaciente',
            name='coleterol_total',
        ),
        migrations.AddField(
            model_name='dadospaciente',
            name='colesterol_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
